wording & tweaks to readme.md
Sequal32/yourcontrols pull request #88
Opened 2021-03-04 21:20 UTC by Stillstellung

- Made some minor clarifying changes to the **Weather** related information in readme.md
- Added line items for slew mode behavior to the will sync and wont sync sections

2021-03-05 15:21 UTC, Sequal32 requested changes

2021-03-05 15:21 UTC, Sequal32 commented on Readme.md
> +* Speed when Weather is not the same across users (ISA/Temperature difference)
weather should be lowercased

2021-03-05 15:21 UTC, Sequal32 commented on Readme.md
> +* Position/Rotation when changed by Slew Mode
I don't think this is needed as changing position/rotation in slew mode is still the same as position/rotation on its own

2021-03-05 16:07 UTC, Stillstellung reviewed
@Sequal32 
sounds good to me on both accounts. 
mostly, was just surprised that slew mode synced, but it does make sense if your code is syncing positional data. not sure why I was surprised! hah

2021-03-06 03:55 UTC, Sequal32 commented
haha that's great - if you'd like to finish this up by making the changes then adding on another commit, I can approve and then merge it

2021-04-02 23:58 UTC, closed without merging